### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by DucPhan13** [quantosapplications/dart_alphanum_comparator#3]
I have an array that contains `[1A, 10A, 2A, A1, A10, A2]`. The `sort` returns `[1A, 2A, A1, A2, 10A, A10]` which is not an expected output. The expected output should be `[1A, 2A, 10A, A1, A2, A10]`

**Comment by vaimikpatel2908** [comment]
I had a similar issue but I found a quick fix for it. 

you can use the following solution in combination with this package.

this works for me at this moment and also works for the case mentioned ablove.

```
bool isStartsWithNumber(String s) {
  RegExp numberRegEx = RegExp(r'[0-9]');

  return s.startsWith(numberRegEx);
}

int alphanumSorter(String s1, String s2) {
  bool isS1startWithNumber = isStartsWithNumber(s1);
  bool isS2startWithNumber = isStartsWithNumber(s2);

  if (isS1startWithNumber && !isS2startWithNumber) {
    return -1;
  } else if (isS2startWithNumber && !isS1startWithNumber) {
    return 1;
  }

  return AlphanumComparator.compare(s1, s2);
}

```

**Comment by ftognetto** [comment]
Hi i have added a new static method to sort num firsts, thanks to @vaimikpatel2908

**Comment by qforce85** [comment]
See [here](https://github.com/ftognetto/alphanum_comparator/issues/5) for a proper fix for this bug.
